<!DOCTYPE html>
<!--
 | Generated by Apache Maven Doxia at 18 September 2019
 | Rendered using Apache Maven Fluido Skin 1.3.0
-->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta charset="iso-8859-1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Apache Commons Documentation Team" />
    <meta name="Date-Revision-yyyymmdd" content="20190918" />
    <meta http-equiv="Content-Language" content="en" />
    <title>Commons Configuration &#x2013; Download Apache Commons Configuration</title>

  <link rel="stylesheet" href="./css/bootstrap.min.css" type="text/css" />
  <link rel="stylesheet" href="./css/site.css" type="text/css" />
    <link rel="stylesheet" href="./css/print.css" media="print" />

  <script type="text/javascript" src="./js/jquery.min.js"></script>
  <script type="text/javascript" src="./js/bootstrap.min.js"></script>
  <script type="text/javascript" src="./js/prettify.min.js"></script>
  <script type="text/javascript" src="./js/site.js"></script>

              
      </head>

  <body class="composite">
                          <a href="http://commons.apache.org/" id="bannerLeft" title="Apache Commons logo">
                                                                                        <img class="logo-left" src="./images/commons-logo.png"  alt="Apache Commons logo"/>
                </a>
                                              <a href="index.html" id="bannerRight">
                                                                                                <img class="logo-right" src="images/logo.png"  alt="Commons Configuration"/>
                </a>
          <div class="clear"></div>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="https://commons.apache.org/proper/commons-configuration/">Apache Commons Configuration &trade;</a>
          <ul class="nav">      
                    
            <li id="publishDate">Last Published: 18 September 2019</li>
      <li class="divider">|</li> <li id="projectVersion">Version: 2.6.1-SNAPSHOT</li>
  </ul>
                    <div class="pull-right">  <ul class="nav">
            <li>
                  <a href="http://www.apachecon.com/" class="externalLink" title="ApacheCon">
    ApacheCon</a>
      </li>
          <li>
                  <a href="http://www.apache.org" class="externalLink" title="Apache">
    Apache</a>
      </li>
          <li>
                  <a href="http://commons.apache.org/" class="externalLink" title="Commons">
    Commons</a>
      </li>
    </ul>
</div>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <table class="layout-table">
        <tr>
          <td class="sidebar">
            <div class="well sidebar-nav">
                    <ul class="nav nav-list">
                                  <li class="nav-header">Configuration</li>
                                        <li class="none">
                  <a href="index.html" title="Overview">
    Overview</a>
          </li>
                             <li class="none">
                  <a href="../../configuration/download_configuration.cgi" title="Download">
    Download</a>
          </li>
                             <li class="none">
                  <a href="issue-tracking.html" title="Issue Tracking">
    Issue Tracking</a>
          </li>
                 </ul>
      <ul class="nav nav-list">
                                  <li class="nav-header">Documentation</li>
                                        <li class="none">
                  <a href="building.html" title="Building">
    Building</a>
          </li>
                             <li class="none">
                  <a href="changes-report.html" title="Release History">
    Release History</a>
          </li>
                                                                                                                                     <li class="collapsed">
                  <a href="index.html" title="2.6.1-SNAPSHOT">
    2.6.1-SNAPSHOT</a>
                    </li>
                                                                                                                   <li class="collapsed">
                  <a href="index.html" title="1.10">
    1.10</a>
                    </li>
                 </ul>
      <ul class="nav nav-list">
                                        <li class="nav-header"><i class="icon-info-sign"></i>Project Documentation</li>
                                                                                                                                                                                                                                                                              <li class="collapsed">
                  <a href="project-info.html" title="Project Information">
    Project Information</a>
                    </li>
                                                                                                                                                                                                                                                                                                       <li class="collapsed">
                  <a href="project-reports.html" title="Project Reports">
    Project Reports</a>
                    </li>
                 </ul>
      <ul class="nav nav-list">
                                  <li class="nav-header">Commons</li>
                                        <li class="none">
                  <a href="http://commons.apache.org/" class="externalLink" title="Home">
    Home</a>
          </li>
                             <li class="none">
                  <a href="http://www.apache.org/licenses/" class="externalLink" title="License">
    License</a>
          </li>
                                                                               <li class="collapsed">
                  <a href="http://commons.apache.org/components.html" class="externalLink" title="Components">
    Components</a>
                    </li>
                                                                               <li class="collapsed">
                  <a href="http://commons.apache.org/sandbox/index.html" class="externalLink" title="Sandbox">
    Sandbox</a>
                    </li>
                                                                               <li class="collapsed">
                  <a href="http://commons.apache.org/dormant/index.html" class="externalLink" title="Dormant">
    Dormant</a>
                    </li>
                 </ul>
      <ul class="nav nav-list">
                                  <li class="nav-header">General Information</li>
                                        <li class="none">
                  <a href="http://commons.apache.org/security.html" class="externalLink" title="Security">
    Security</a>
          </li>
                             <li class="none">
                  <a href="http://commons.apache.org/volunteering.html" class="externalLink" title="Volunteering">
    Volunteering</a>
          </li>
                             <li class="none">
                  <a href="http://commons.apache.org/patches.html" class="externalLink" title="Contributing Patches">
    Contributing Patches</a>
          </li>
                             <li class="none">
                  <a href="http://commons.apache.org/building.html" class="externalLink" title="Building Components">
    Building Components</a>
          </li>
                             <li class="none">
                  <a href="http://commons.apache.org/commons-parent-pom.html" class="externalLink" title="Commons Parent Pom">
    Commons Parent Pom</a>
          </li>
                             <li class="none">
                  <a href="http://commons.apache.org/build-plugin/index.html" class="externalLink" title="Commons Build Plugin">
    Commons Build Plugin</a>
          </li>
                             <li class="none">
                  <a href="http://commons.apache.org/releases/index.html" class="externalLink" title="Releasing Components">
    Releasing Components</a>
          </li>
                             <li class="none">
                  <a href="http://wiki.apache.org/commons/FrontPage" class="externalLink" title="Wiki">
    Wiki</a>
          </li>
                 </ul>
      <ul class="nav nav-list">
                                  <li class="nav-header">ASF</li>
                                        <li class="none">
                  <a href="http://www.apache.org/foundation/how-it-works.html" class="externalLink" title="How the ASF works">
    How the ASF works</a>
          </li>
                             <li class="none">
                  <a href="http://www.apache.org/foundation/getinvolved.html" class="externalLink" title="Get Involved">
    Get Involved</a>
          </li>
                             <li class="none">
                  <a href="http://www.apache.org/dev/" class="externalLink" title="Developer Resources">
    Developer Resources</a>
          </li>
                             <li class="none">
                  <a href="http://www.apache.org/foundation/policies/conduct.html" class="externalLink" title="Code of Conduct">
    Code of Conduct</a>
          </li>
                             <li class="none">
                  <a href="http://www.apache.org/foundation/sponsorship.html" class="externalLink" title="Sponsorship">
    Sponsorship</a>
          </li>
                             <li class="none">
                  <a href="http://www.apache.org/foundation/thanks.html" class="externalLink" title="Thanks">
    Thanks</a>
          </li>
                 </ul>
              </div>
            <div id="poweredBy">
                                                                                                                    <a href="http://www.apache.org/events/current-event.html" title="ApacheCon" class="builtBy">
        <img class="builtBy"  alt="ApacheCon" src="http://www.apache.org/events/current-event-125x125.png"    />
      </a>
                                                                                                    <a href="http://maven.apache.org/" title="Maven" class="builtBy">
        <img class="builtBy"  alt="Maven" src="http://maven.apache.org/images/logos/maven-feather.png"    />
      </a>
                      </div>
          </td>
          <td class="content">
            
  
    <div class="section">
<h2><a name="Download_Apache_Commons_Configuration"></a>Download Apache Commons Configuration</h2>
    
<div class="section">
<h3><a name="Using_a_Mirror"></a>Using a Mirror</h3>
      
<p>
        We recommend you use a mirror to download our release
        builds, but you <b>must</b> <a class="externalLink" href="http://www.apache.org/info/verification.html">verify the integrity</a> of
        the downloaded files using signatures downloaded from our main
        distribution directories. Recent releases (48 hours) may not yet
        be available from all the mirrors.
      </p>

      
<p>
        You are currently using <b>http://mirrors.estointernet.in/apache/</b>.  If you
        encounter a problem with this mirror, please select another
        mirror.  If all mirrors are failing, there are <i>backup</i>
        mirrors (at the end of the mirrors list) that should be
        available.
        <br /></br>
        
      </p>

      <form action="" method="get" id="SelectMirror">
        
<p>
          Other mirrors:
          <select name="Preferred">
          <option value="http://apachemirror.wuchna.com/">http://apachemirror.wuchna.com/</option><option value="http://mirrors.estointernet.in/apache/">http://mirrors.estointernet.in/apache/</option><option value="https://www-eu.apache.org/dist/">https://www-eu.apache.org/dist/ (backup)</option><option value="https://www-us.apache.org/dist/">https://www-us.apache.org/dist/ (backup)</option>
          </select>
          <input type="submit" value="Change"></input>
        </p>
      </form>

      
<p>
        It is essential that you
        <a class="externalLink" href="https://www.apache.org/info/verification.html">verify the integrity</a>
        of downloaded files, preferably using the <tt>PGP</tt> signature (<tt>*.asc</tt> files);
        failing that using the <tt>SHA512</tt> hash (<tt>*.sha512</tt> checksum files).
      </p>
      
<p>
        The <a class="externalLink" href="https://www.apache.org/dist/commons/KEYS">KEYS</a>
        file contains the public PGP keys used by Apache Commons developers
        to sign releases.
      </p>
    </div>
    </div>
    
<div class="section">
<h2><a name="Apache_Commons_Configuration_2.6_.28reworked_2.x_version.29"></a>Apache Commons Configuration 2.6 (reworked 2.x version)</h2>
      
<div class="section">
<h3><a name="Binaries"></a>Binaries</h3>
        
<table border="0" class="bodyTable">
          
<tr class="a">
              
<td><a href="http://mirrors.estointernet.in/apache//commons/configuration/binaries/commons-configuration2-2.6-bin.tar.gz">commons-configuration2-2.6-bin.tar.gz</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/binaries/commons-configuration2-2.6-bin.tar.gz.sha512">sha512</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/binaries/commons-configuration2-2.6-bin.tar.gz.asc">pgp</a></td>
          </tr>
          
<tr class="b">
              
<td><a href="http://mirrors.estointernet.in/apache//commons/configuration/binaries/commons-configuration2-2.6-bin.zip">commons-configuration2-2.6-bin.zip</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/binaries/commons-configuration2-2.6-bin.zip.sha512">sha512</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/binaries/commons-configuration2-2.6-bin.zip.asc">pgp</a></td>
          </tr>
        </table>
      </div>
      
<div class="section">
<h3><a name="Source"></a>Source</h3>
        
<table border="0" class="bodyTable">
          
<tr class="a">
              
<td><a href="http://mirrors.estointernet.in/apache//commons/configuration/source/commons-configuration2-2.6-src.tar.gz">commons-configuration2-2.6-src.tar.gz</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/source/commons-configuration2-2.6-src.tar.gz.sha512">sha512</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/source/commons-configuration2-2.6-src.tar.gz.asc">pgp</a></td>
          </tr>
          
<tr class="b">
              
<td><a href="http://mirrors.estointernet.in/apache//commons/configuration/source/commons-configuration2-2.6-src.zip">commons-configuration2-2.6-src.zip</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/source/commons-configuration2-2.6-src.zip.sha512">sha512</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/source/commons-configuration2-2.6-src.zip.asc">pgp</a></td>
          </tr>
        </table>
      </div>
    </div>
    
<div class="section">
<h2><a name="Apache_Commons_Configuration_1.10_.28old_1.x_version.29"></a>Apache Commons Configuration 1.10 (old 1.x version)</h2>
      
<div class="section">
<h3><a name="Binaries"></a>Binaries</h3>
        
<table border="0" class="bodyTable">
          
<tr class="a">
              
<td><a href="http://mirrors.estointernet.in/apache//commons/configuration/binaries/commons-configuration-1.10-bin.tar.gz">commons-configuration-1.10-bin.tar.gz</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/binaries/commons-configuration-1.10-bin.tar.gz.sha256">sha256</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/binaries/commons-configuration-1.10-bin.tar.gz.asc">pgp</a></td>
          </tr>
          
<tr class="b">
              
<td><a href="http://mirrors.estointernet.in/apache//commons/configuration/binaries/commons-configuration-1.10-bin.zip">commons-configuration-1.10-bin.zip</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/binaries/commons-configuration-1.10-bin.zip.sha256">sha256</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/binaries/commons-configuration-1.10-bin.zip.asc">pgp</a></td>
          </tr>
        </table>
      </div>
      
<div class="section">
<h3><a name="Source"></a>Source</h3>
        
<table border="0" class="bodyTable">
          
<tr class="a">
              
<td><a href="http://mirrors.estointernet.in/apache//commons/configuration/source/commons-configuration-1.10-src.tar.gz">commons-configuration-1.10-src.tar.gz</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/source/commons-configuration-1.10-src.tar.gz.sha256">sha256</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/source/commons-configuration-1.10-src.tar.gz.asc">pgp</a></td>
          </tr>
          
<tr class="b">
              
<td><a href="http://mirrors.estointernet.in/apache//commons/configuration/source/commons-configuration-1.10-src.zip">commons-configuration-1.10-src.zip</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/source/commons-configuration-1.10-src.zip.sha256">sha256</a></td>
              
<td><a class="externalLink" href="https://www.apache.org/dist/commons/configuration/source/commons-configuration-1.10-src.zip.asc">pgp</a></td>
          </tr>
        </table>
      </div>
    </div>
    
<div class="section">
<h2><a name="Archives"></a>Archives</h2>
        
<p>
          Older releases can be obtained from the archives.
        </p>
        
<ul>
          
<li class="download"><a href="http://mirrors.estointernet.in/apache//commons/configuration/">browse download area</a></li>
          
<li><a class="externalLink" href="https://archive.apache.org/dist/commons/configuration/">archives...</a></li>
        </ul>
    </div>
  

          </td>
        </tr>
      </table>
    </div>

    <div class="footer">
      <p>Copyright &copy;                    2001-2019
                        <a href="https://www.apache.org/">The Apache Software Foundation</a>.
            All Rights Reserved.</p>
                </div>
  </body>

</html>